name: Minha Primeira Linha de Montagem

on:
  push:
    branches: [ main ]
    
jobs:
 build-e-test:
   runs-on: ubuntu-latest

     steps:
     - name: 1. Pegar o chassi do carro (código-fonte)
      uses: actions/checkout@v3

     - name: 2. Estação de Build (Montagem)
        run: echo "construindo o projeto... verificando se todas as peças se encaixam!"

      - name: 3. Estação de Teste (Controle de Qualidade)
        run: echo "rodando os testes automatizados... verificando se a porta abre e fecha!"
